//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'GXResourceGenerator' tool.
//
//     (!) Changes to this file will be lost the next time the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Artech.Patterns.Category.Resources
{
	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	public static class Images
	{
		private static global::Artech.Common.Localization.CachingResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (global::System.Object.ReferenceEquals(resourceMan, null)) 
				{
					global::Artech.Common.Localization.CachingResourceManager temp = new global::Artech.Common.Localization.CachingResourceManager("Artech.Patterns.Category.Resources.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}

				return resourceMan;
			}
		}

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture 
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'ObjectAttribute'
		/// </summary>
		public static System.Drawing.Icon ObjectAttribute
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("ObjectAttribute", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'ObjectTransaction'
		/// </summary>
		public static System.Drawing.Icon ObjectTransaction
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("ObjectTransaction", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'PatternCategory'
		/// </summary>
		public static System.Drawing.Icon PatternCategory
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("PatternCategory", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'StructureLevel'
		/// </summary>
		public static System.Drawing.Icon StructureLevel
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("StructureLevel", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'TextBlock'
		/// </summary>
		public static System.Drawing.Icon TextBlock
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("TextBlock", resourceCulture);
			}
		}
	}
}