//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'GXResourceGenerator' tool.
//
//     (!) Changes to this file will be lost the next time the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Artech.Patterns.Category.Resources
{
	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	public static class Messages
	{
		private static global::Artech.Common.Localization.CachingResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (global::System.Object.ReferenceEquals(resourceMan, null)) 
				{
					global::Artech.Common.Localization.CachingResourceManager temp = new global::Artech.Common.Localization.CachingResourceManager("Artech.Patterns.Category.Resources.Messages", typeof(Messages).Assembly);
					resourceMan = temp;
				}

				return resourceMan;
			}
		}

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture 
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Action &apos;Export&apos; cannot be in a component that is not a grid.'
		/// </summary>
		public static System.String ActionExportNotInGrid
		{
			get
			{
				return (System.String)ResourceManager.GetString("ActionExportNotInGrid", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.'
		/// </summary>
		public static System.String ActionNeedsObject
		{
			get
			{
				return (System.String)ResourceManager.GetString("ActionNeedsObject", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.', formatted using the specified arguments.
		/// </summary>
		public static string FormatActionNeedsObject(object arg0)
		{
			return FormatActionNeedsObject(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.', formatted using the specified arguments.
		/// </summary>
		public static string FormatActionNeedsObject(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ActionNeedsObject, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Parent of action &apos;{0}&apos; is not an IWorkWithComponent instance.'
		/// </summary>
		public static System.String ActionNotInComponent
		{
			get
			{
				return (System.String)ResourceManager.GetString("ActionNotInComponent", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parent of action &apos;{0}&apos; is not an IWorkWithComponent instance.', formatted using the specified arguments.
		/// </summary>
		public static string FormatActionNotInComponent(object arg0)
		{
			return FormatActionNotInComponent(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parent of action &apos;{0}&apos; is not an IWorkWithComponent instance.', formatted using the specified arguments.
		/// </summary>
		public static string FormatActionNotInComponent(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ActionNotInComponent, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.'
		/// </summary>
		public static System.String ContextVariableInvalidType
		{
			get
			{
				return (System.String)ResourceManager.GetString("ContextVariableInvalidType", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.', formatted using the specified arguments.
		/// </summary>
		public static string FormatContextVariableInvalidType(object arg0)
		{
			return FormatContextVariableInvalidType(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.', formatted using the specified arguments.
		/// </summary>
		public static string FormatContextVariableInvalidType(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ContextVariableInvalidType, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Current Settings have not been set.'
		/// </summary>
		public static System.String CurrentSettingsNotSet
		{
			get
			{
				return (System.String)ResourceManager.GetString("CurrentSettingsNotSet", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.'
		/// </summary>
		public static System.String ParameterConditionNeedsAttribute
		{
			get
			{
				return (System.String)ResourceManager.GetString("ParameterConditionNeedsAttribute", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.', formatted using the specified arguments.
		/// </summary>
		public static string FormatParameterConditionNeedsAttribute(object arg0)
		{
			return FormatParameterConditionNeedsAttribute(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.', formatted using the specified arguments.
		/// </summary>
		public static string FormatParameterConditionNeedsAttribute(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ParameterConditionNeedsAttribute, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Work With parent object must be a transaction.'
		/// </summary>
		public static System.String ParentMustBeTransaction
		{
			get
			{
				return (System.String)ResourceManager.GetString("ParentMustBeTransaction", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Unexpected parent getting name for Export Procedure'
		/// </summary>
		public static System.String UnexpectedExportParent
		{
			get
			{
				return (System.String)ResourceManager.GetString("UnexpectedExportParent", resourceCulture);
			}
		}
	}
}